# Generated by Django 5.2.8 on 2025-11-21 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='会社名')),
                ('contact_person', models.CharField(max_length=100, verbose_name='担当者名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='業種')),
                ('company_size', models.CharField(blank=True, max_length=50, verbose_name='企業規模')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案件名')),
                ('status', models.CharField(choices=[('inquiry', '初回相談'), ('hearing', 'ヒアリング中'), ('proposal', '提案作成中'), ('quotation', '見積提示'), ('negotiation', '商談中'), ('handover', 'エンジニア引継ぎ'), ('in_progress', '実施中'), ('completed', '完了'), ('on_hold', '保留'), ('lost', '失注')], default='inquiry', max_length=20, verbose_name='ステータス')),
                ('consultation_content', models.TextField(blank=True, verbose_name='ご相談内容')),
                ('proposal_content', models.TextField(blank=True, verbose_name='提案内容')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='見積金額（円）')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始予定日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完了予定日')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.client', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記録日時')),
                ('activity_type', models.CharField(choices=[('meeting', '打ち合わせ'), ('phone', '電話'), ('email', 'メール'), ('proposal', '提案作成'), ('quotation', '見積作成'), ('presentation', 'プレゼン'), ('other', 'その他')], max_length=100, verbose_name='活動種別')),
                ('content', models.TextField(verbose_name='内容')),
                ('next_action', models.TextField(blank=True, verbose_name='次回アクション')),
                ('created_by', models.CharField(default='担当者', max_length=100, verbose_name='記録者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '進捗記録',
                'verbose_name_plural': '進捗記録',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_type', models.CharField(choices=[('staff_notsu', '@Staff_Notsuさんへの引継ぎ'), ('uragami', '浦上泰弘さんへの引継ぎ'), ('engineer', 'その他エンジニアへの引継ぎ')], max_length=20, verbose_name='引継ぎ先')),
                ('handover_to', models.CharField(max_length=100, verbose_name='引継ぎ先担当者名')),
                ('handover_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='引継ぎ日時')),
                ('handover_content', models.TextField(verbose_name='引継ぎ内容')),
                ('technical_requirements', models.TextField(blank=True, verbose_name='技術要件')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_completed', models.BooleanField(default=False, verbose_name='引継ぎ完了')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '引継ぎ記録',
                'verbose_name_plural': '引継ぎ記録',
                'ordering': ['-handover_date'],
            },
        ),
        migrations.CreateModel(
            name='EngineerHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100, verbose_name='エンジニア名')),
                ('handoff_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='バトンタッチ日時')),
                ('technical_scope', models.TextField(verbose_name='技術的な対応範囲')),
                ('current_status', models.TextField(verbose_name='現在の状況')),
                ('client_requirements', models.TextField(verbose_name='顧客要件')),
                ('timeline', models.TextField(blank=True, verbose_name='スケジュール')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='予算（円）')),
                ('special_notes', models.TextField(blank=True, verbose_name='特記事項')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='エンジニア承認済み')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_handoffs', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': 'エンジニアバトンタッチ',
                'verbose_name_plural': 'エンジニアバトンタッチ',
                'ordering': ['-handoff_date'],
            },
        ),
    ]
